package pro.modelo.entidad;
// Generated 24/05/2015 11:18:57 AM by Hibernate Tools 4.3.1



/**
 * Aula generated by hbm2java
 */
public class Aula  implements java.io.Serializable {


     private String idAula;
     private String nombre;
     private String descripcion;
     private String estado;

    public Aula() {
    }

	
    public Aula(String idAula, String nombre, String estado) {
        this.idAula = idAula;
        this.nombre = nombre;
        this.estado = estado;
    }
    public Aula(String idAula, String nombre, String descripcion, String estado) {
       this.idAula = idAula;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public String getIdAula() {
        return this.idAula;
    }
    
    public void setIdAula(String idAula) {
        this.idAula = idAula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


