package pro.modelo.entidad;
// Generated 07/06/2015 12:41:39 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Campana generated by hbm2java
 */
public class Campana  implements java.io.Serializable {


     private String idCampana;
     private String nombre;
     private String semestre;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;

    public Campana() {
    }

	
    public Campana(String idCampana, String nombre) {
        this.idCampana = idCampana;
        this.nombre = nombre;
    }
    public Campana(String idCampana, String nombre, String semestre, Date fechaInicio, Date fechaFin, String estado) {
       this.idCampana = idCampana;
       this.nombre = nombre;
       this.semestre = semestre;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
    }
   
    public String getIdCampana() {
        return this.idCampana;
    }
    
    public void setIdCampana(String idCampana) {
        this.idCampana = idCampana;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


