package pro.modelo.entidad;
// Generated 24/05/2015 11:18:57 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Campana generated by hbm2java
 */
public class Campana  implements java.io.Serializable {


     private String idCampana;
     private String nombre;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;

    public Campana() {
    }

	
    public Campana(String idCampana, String nombre, String estado) {
        this.idCampana = idCampana;
        this.nombre = nombre;
        this.estado = estado;
    }
    public Campana(String idCampana, String nombre, Date fechaInicio, Date fechaFin, String estado) {
       this.idCampana = idCampana;
       this.nombre = nombre;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
    }
   
    public String getIdCampana() {
        return this.idCampana;
    }
    
    public void setIdCampana(String idCampana) {
        this.idCampana = idCampana;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


