package pro.modelo.entidad;
// Generated 17/06/2015 05:32:42 PM by Hibernate Tools 4.3.1



/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private String idCurso;
     private String nombre;
     private String horaPedagogica;

    public Curso() {
    }

	
    public Curso(String idCurso, String nombre) {
        this.idCurso = idCurso;
        this.nombre = nombre;
    }
    public Curso(String idCurso, String nombre, String horaPedagogica) {
       this.idCurso = idCurso;
       this.nombre = nombre;
       this.horaPedagogica = horaPedagogica;
    }
   
    public String getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(String idCurso) {
        this.idCurso = idCurso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getHoraPedagogica() {
        return this.horaPedagogica;
    }
    
    public void setHoraPedagogica(String horaPedagogica) {
        this.horaPedagogica = horaPedagogica;
    }




}


