package pro.modelo.entidad;
// Generated 24/05/2015 11:18:57 AM by Hibernate Tools 4.3.1



/**
 * Turno generated by hbm2java
 */
public class Turno  implements java.io.Serializable {


     private String idTurno;
     private String nombre;
     private String horaInicio;
     private String horaFin;
     private String diaSemana;
     private String estado;

    public Turno() {
    }

	
    public Turno(String idTurno, String nombre, String estado) {
        this.idTurno = idTurno;
        this.nombre = nombre;
        this.estado = estado;
    }
    public Turno(String idTurno, String nombre, String horaInicio, String horaFin, String diaSemana, String estado) {
       this.idTurno = idTurno;
       this.nombre = nombre;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.diaSemana = diaSemana;
       this.estado = estado;
    }
   
    public String getIdTurno() {
        return this.idTurno;
    }
    
    public void setIdTurno(String idTurno) {
        this.idTurno = idTurno;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(String horaInicio) {
        this.horaInicio = horaInicio;
    }
    public String getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(String horaFin) {
        this.horaFin = horaFin;
    }
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


