package pro.modelo.entidad;
// Generated 17/06/2015 05:32:42 PM by Hibernate Tools 4.3.1



/**
 * Turno generated by hbm2java
 */
public class Turno  implements java.io.Serializable {


     private String idTurno;
     private String nombre;
     private String estado;

    public Turno() {
    }

	
    public Turno(String idTurno, String nombre) {
        this.idTurno = idTurno;
        this.nombre = nombre;
    }
    public Turno(String idTurno, String nombre, String estado) {
       this.idTurno = idTurno;
       this.nombre = nombre;
       this.estado = estado;
    }
   
    public String getIdTurno() {
        return this.idTurno;
    }
    
    public void setIdTurno(String idTurno) {
        this.idTurno = idTurno;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


